sudo: required
services:
  - docker

before_install:
  - docker build -t orkhanhuseynli/multi-node-app -f ./client/Dockerfile.dev ./client

notifications:
  email: false

script:
  - docker run -e CI=true orkhanhuseynli/multi-node-app npm run test

after_success:
  - docker build -t orkhanhuseynli/multi-client ./client
  - docker build -t orkhanhuseynli/multi-nginx ./nginx
  - docker build -t orkhanhuseynli/multi-server ./server
  - docker build -t orkhanhuseynli/multi-worker ./worker
  # log in to the docker CLI
  # use credentials from travis environment
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push orkhanhuseynli/multi-client
  - docker push orkhanhuseynli/multi-nginx
  - docker push orkhanhuseynli/multi-server
  - docker push orkhanhuseynli/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-500081795556
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
